table media_all
	lineageTag: 3722d6ea-7495-4cfa-ae4d-15684e2d2f6d

	measure 'sum popularity' = sum(media_all[popularity])
		lineageTag: 615bc4f2-792e-4fcf-8e87-059a28ad20cf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'vote average' = AVERAGE(media_all[vote_average])
		lineageTag: 8984b48e-5747-4d0f-a183-01e8f6aff2a6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'average popularity' = AVERAGE(media_all[popularity])
		lineageTag: bfe7277f-aa99-43e7-a562-c63670858d92

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'average vote count' = AVERAGE(media_all[vote_count])
		lineageTag: 538fd209-1207-4a7d-a06a-ab193ae91d9b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'sum vote count' = SUM(media_all[vote_count])
		formatString: 0
		lineageTag: 56fe91b5-6aa0-437b-904d-98b6e4f93f70

	column backdrop_path
		dataType: string
		lineageTag: 67cb56df-1b23-40b8-a095-a32b7d0c74b1
		summarizeBy: none
		sourceColumn: backdrop_path

		annotation SummarizationSetBy = Automatic

	column genre_ids
		dataType: string
		lineageTag: 629fcb84-9985-4013-9417-b8c030b55022
		summarizeBy: none
		sourceColumn: genre_ids

		annotation SummarizationSetBy = Automatic

	column media_id
		dataType: int64
		formatString: 0
		lineageTag: 3f71547e-cb1c-4d09-923d-688b84e7fd9d
		summarizeBy: sum
		sourceColumn: media_id

		annotation SummarizationSetBy = Automatic

	column origin_country
		dataType: string
		lineageTag: bb718c83-408f-41bc-85c2-afdbd4ea842a
		summarizeBy: none
		sourceColumn: origin_country

		annotation SummarizationSetBy = Automatic

	column original_language
		dataType: string
		lineageTag: 2f206c56-b99d-4350-8f74-08336e3cafa7
		summarizeBy: none
		sourceColumn: original_language

		annotation SummarizationSetBy = Automatic

	column original_name
		dataType: string
		lineageTag: 7ca8fc38-0ab8-40f4-985c-e4b302366567
		summarizeBy: none
		sourceColumn: original_name

		annotation SummarizationSetBy = Automatic

	column overview
		dataType: string
		lineageTag: 6f95692e-38fe-4630-9d0a-107eb6cbac7b
		summarizeBy: none
		sourceColumn: overview

		annotation SummarizationSetBy = Automatic

	column popularity
		dataType: double
		lineageTag: a3b15028-8428-463d-917c-4f317e177b95
		summarizeBy: sum
		sourceColumn: popularity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column poster_path
		dataType: string
		lineageTag: 2d6a90ae-7bfd-4e3a-bc16-3ab794c5e85e
		summarizeBy: none
		sourceColumn: poster_path

		annotation SummarizationSetBy = Automatic

	column first_air_date
		dataType: string
		lineageTag: 53dc00ca-6c0f-454b-86cb-26e1a1b0fae6
		summarizeBy: none
		sourceColumn: first_air_date

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: a7ad0437-a5bc-4846-9274-94c5889d6ebd
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column vote_average
		dataType: double
		lineageTag: 9c64088d-a23d-43a7-8b55-2244cf38521e
		summarizeBy: sum
		sourceColumn: vote_average

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column vote_count
		dataType: int64
		formatString: 0
		lineageTag: d3c93419-c21e-4dac-b61b-de87bc2e528c
		summarizeBy: sum
		sourceColumn: vote_count

		annotation SummarizationSetBy = Automatic

	column media_type
		dataType: string
		lineageTag: c365ea4e-2408-480e-acdf-61c349d31d22
		summarizeBy: none
		sourceColumn: media_type

		annotation SummarizationSetBy = Automatic

	column dataset
		dataType: string
		lineageTag: fd11a405-a105-478c-8da5-9ac97c736289
		summarizeBy: none
		sourceColumn: dataset

		annotation SummarizationSetBy = Automatic

	column title
		dataType: string
		lineageTag: 9ca66ae4-963a-42c8-ad82-b89bb436117a
		summarizeBy: none
		sourceColumn: title

		annotation SummarizationSetBy = Automatic

	column original_title
		dataType: string
		lineageTag: 5ced69fb-d8d0-4bfd-98fc-9110b8c0c7f9
		summarizeBy: none
		sourceColumn: original_title

		annotation SummarizationSetBy = Automatic

	column release_date
		dataType: string
		lineageTag: 6291a652-c4e9-4cc4-9597-18f9d368996d
		summarizeBy: none
		sourceColumn: release_date

		annotation SummarizationSetBy = Automatic

	column video
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ff1e6306-a632-4057-af9a-c0a2bb8587d0
		summarizeBy: none
		sourceColumn: video

		annotation SummarizationSetBy = Automatic

	column media_type_id
		dataType: string
		lineageTag: a5b24493-67c3-4b59-bf97-f42628855a77
		summarizeBy: none
		sourceColumn: media_type_id

		annotation SummarizationSetBy = Automatic

	column poster_path_full
		dataType: string
		lineageTag: 81734de0-0e10-47d9-94ce-582cc1529a56
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: poster_path_full

		annotation SummarizationSetBy = Automatic

	column genres
		dataType: string
		lineageTag: 209389ee-0cdd-4c71-82a4-a8d25a035390
		summarizeBy: none
		sourceColumn: genres

		annotation SummarizationSetBy = Automatic

	column title_name
		dataType: string
		lineageTag: 66bf53de-ba8f-4646-a6b4-d253d84f7cae
		summarizeBy: none
		sourceColumn: title_name

		annotation SummarizationSetBy = Automatic

	column 'Popularity Rank'
		dataType: int64
		formatString: 0
		lineageTag: 15c8a638-9ff5-4f99-8f67-7c4d4f1661e3
		summarizeBy: sum
		sourceColumn: Popularity Rank

		annotation SummarizationSetBy = Automatic

	column 'Date of Release'
		dataType: dateTime
		formatString: Long Date
		lineageTag: b1703efe-c158-4503-88af-59e316b7a93d
		summarizeBy: none
		sourceColumn: Date of Release

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition media_all = m
		mode: import
		source =
				let
				  Source = PostgreSQL.Database("localhost:5432", "social_dash_db"),
				  #"Navigation 1" = Source{[Schema = "public", Item = "media_all"]}[Data],
				    #"Sorted Rows" = Table.Sort(#"Navigation 1",{{"media_type_id", Order.Ascending}}),
				    #"Removed Duplicates" = Table.Distinct(#"Sorted Rows"),
				    #"Removed Duplicates1" = Table.Distinct(#"Removed Duplicates", {"title", "media_type_id"}),
				    #"Added Conditional Column" = Table.AddColumn(#"Removed Duplicates1", "title_name", each if [title] = null then [name] else [title]),
				    #"Sorted Rows1" = Table.Sort(#"Added Conditional Column",{{"popularity", Order.Descending}}),
				    #"Added Index" = Table.AddIndexColumn(#"Sorted Rows1", "Popularity Rank", 1, 1, Int64.Type),
				    #"Extracted Text Between Delimiters" = Table.TransformColumns(#"Added Index", {{"genres", each Text.BetweenDelimiters(_, "{", "}"), type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Extracted Text Between Delimiters"," ","_",Replacer.ReplaceText,{"genres"}),
				    #"Added Conditional Column1" = Table.AddColumn(#"Replaced Value", "Date of Release", each if [release_date] = null then [first_air_date] else [release_date]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Conditional Column1",{{"Date of Release", type date}}),
				    #"Sorted Rows2" = Table.Sort(#"Changed Type",{{"Date of Release", Order.Ascending}})
				in
				  #"Sorted Rows2"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

